context("interactive map")

testthat::test_that("function draw", {

  testthat::expect_is(draw(data.frame()), "leaflet")
  testthat::expect_is(draw(data.frame(Latitude = NA, ID = "a")), "leaflet")
  testthat::expect_is(draw(data.frame(Latitude = 45,
                                      Longitude = 5, ID = "b")), "leaflet")

})

testthat::test_that("function extractMarker", {

  testData <- tibble::tribble(
    ~source,     ~id,               ~description, ~latitude, ~longitude, ~dateLower, ~dateUpper,                                   ~compilationDOI,                                                                                                                                                                                                                                                                                                                                         ~compilationReference, ~compilationDOIAuto, ~d13C, ~d15N,           ~site, ~dateMean, ~dateUncertainty,   ~datingType, ~calibratedDate, ~calibratedDateLower, ~calibratedDateUpper, ~databaseDOI, ~databaseDOIAuto, ~databaseReference, ~measure, ~originalDataDOI, ~originalDataDOIAuto, ~originalDataReference,
    "CIMA",     "1", "Carlo Cocozza Høre k ...",   61.1531,     8.8047,      1075L,      1125L, "http://dx.doi.org/10.1016/s0048-9697(98)00347-7",                                                                                                                                       "Åberg, G., Fosse, G., Stray, H. (1998). Man, nutrition and mobility: A comparison of teeth and bone from the Medieval era and the present from Pb and Sr isotopes. The Science of the Total Environment 224: 109-119.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA",    "10",         "Carlo Cocozza 94",   58.3857,    13.6462,       900L,      1025L,     "http://dx.doi.org/10.1130/abs/2017am-305496",                                                                                                                                                                            "Åborg, D.C. (2013). Hierarchy through Diet. Stable isotope analysis of male graves of the estate church graveyard in Varnhem. Unpublished BA dissertation: Stockholm University.",                  1L, -20.5,    11,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA",   "100",       "Carlo Cocozza 4707",   38.9078,     1.4308,       300L,       700L,     "http://dx.doi.org/10.1007/s12520-018-0656-0", "Alaica, A.K., Schalburg-Clayton, J., Dalton, A., Kranioti, E., Graziani Echávarri, G., Pickard, C. (2019). Variability along the frontier: stable carbon and nitrogen isotope ratio analysis of human remains from the Late Roman–Early Byzantine cemetery site of Joan Planells, Ibiza, Spain. Archaeological and Anthropological Sciences 11: 3783–3796 .",                  1L, -19.3,   9.7,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA",  "1000",      "Carlo Cocozza R5109",   52.3491,     -0.533,       900L,      1066L,            "http://dx.doi.org/10.1002/ajpa.23682",                                                "Beaumont, J., Craig-Atkins, E., Buckberry, J., Haydock, H., Horne, P., Howcroft, R., Mackenzie, K., Montgomery J. (2018). Comparing apples and oranges: Why infant bone collagen may not reflect dietary intake in the same way as dentine collagen. American Journal of Physical Anthropology 167: 524-540.",                  1L, -18.1,  15.2,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10000",      "Carlo Cocozza BG576",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10001",      "Carlo Cocozza BG591",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10002",      "Carlo Cocozza BG314",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10003",      "Carlo Cocozza BG040",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10004",      "Carlo Cocozza BG637",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10005",      "Carlo Cocozza BG567",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10006",      "Carlo Cocozza BG626",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10007",      "Carlo Cocozza BG659",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10008",      "Carlo Cocozza BG534",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10009",      "Carlo Cocozza BG581",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA",  "1001",      "Carlo Cocozza R5109",   52.3491,     -0.533,       900L,      1066L,            "http://dx.doi.org/10.1002/ajpa.23682",                                                "Beaumont, J., Craig-Atkins, E., Buckberry, J., Haydock, H., Horne, P., Howcroft, R., Mackenzie, K., Montgomery J. (2018). Comparing apples and oranges: Why infant bone collagen may not reflect dietary intake in the same way as dentine collagen. American Journal of Physical Anthropology 167: 524-540.",                  1L, -18.7,    14,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10010",      "Carlo Cocozza BG314",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10011",      "Carlo Cocozza BG498",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10012",      "Carlo Cocozza BG386",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10013",      "Carlo Cocozza BG252",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "CIMA", "10014",      "Carlo Cocozza BG433",    54.969,    -1.6104,       680L,      1168L,     "http://dx.doi.org/10.3138/9781487514433-005",                                                                                                                                                                                                    "MacPherson, P.M. (2005). Tracing Change: An Isotopic Investigation of Anglo-Saxon Childhood Diet. Unpublished PhD dissertation. University of Sheffield.",                  1L,    NA,    NA,              NA,        NA,               NA,            NA,              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1000", "Ajdovska Jama 21 , S ...",   45.9667,    15.4833,      4328L,      4055L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.4,     9, "Ajdovska Jama",      5365,               31, "radiocarbon",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1001", "Ajdovska Jama 3 , S  ...",   45.9667,    15.4833,      4340L,      4235L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.6,   8.1, "Ajdovska Jama",      5421,               30, "radiocarbon",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1002", "Ajdovska Jama 6 , S  ...",   45.9667,    15.4833,      4344L,      4244L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.8,     9, "Ajdovska Jama",      5436,               30, "radiocarbon",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1003", "Ajdovska Jama 7 , S  ...",   45.9667,    15.4833,      4448L,      4243L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.3,   8.1, "Ajdovska Jama",      5485,               50, "radiocarbon",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1004", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -22.4,   5.8, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1005", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA,   -21,   6.6, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1006", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.8,   8.2, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1007", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.3,   9.4, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1008", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -21.6,   8.3, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1009", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -21.3,   6.6, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1010", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -22.5,   5.6, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1011", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.9,   8.1, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1012", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.7,   9.3, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1013", "Ajdovska Jama , S Ne ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.5,   7.9, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1014", "Ajdovska Jama 12 , S ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.7,  10.8, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1015", "Ajdovska Jama 14 , S ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.4,  11.5, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1016", "Ajdovska Jama 19 , S ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -22.2,   4.9, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1017", "Ajdovska Jama 20 , S ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -20.5,     9, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1018", "Ajdovska Jama 22 , S ...",   45.9667,    15.4833,      4450L,      4050L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -21.2,   5.6, "Ajdovska Jama",      4250,              100,      "expert",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA,
    "LiVES",  "1019", "Lepenski Vir 2 OxA-1 ...",   44.5611,    22.0242,      4236L,      3974L,                                                NA,                                                                                                                                                                                                                                                                                                                                                            NA,                  NA, -19.5,  10.6,  "Lepenski Vir",      5425,               NA, "radiocarbon",              NA,                   NA,                   NA,           NA,               NA,                 NA,       NA,               NA,                   NA,                     NA
  )


  testMap <- leaflet(testData) %>% addTiles()

  testStyle <-
    list(
      customizeMarkers = TRUE,
      groupingColumn = "source",
      groups = structure(1:2, .Label = c("CIMA",
                                         "LiVES"), class = "factor"),
      colours = c(CIMA = "#F39C12", LiVES = "#D81B60"),
      radiusKm = c(CIMA = 80000, LiVES = 20000),
      opacity = c(0.3, 0.8)
      #shapes = list(CIMA = "circle", LiVES = "square")
    )

  testthat::expect_is(leaflet(testData) %>% addTiles(), "leaflet")
  testthat::expect_is(
    testMap %>%
      addAwesomeMarkers(testData$longitude, testData$latitude,
                        icon = extractMarker(testStyle)[testData$source]),
    "leaflet"
  )
  testthat::expect_is(
    leaflet(testData) %>%
      addTiles() %>%
      addAwesomeMarkers( ~ longitude, ~ latitude, icon = ~ extractMarker(testStyle)[testData$source]),
    "leaflet"
  )

  testthat::expect_is(
    testMap %>%
      addCustomCircles(testData, testStyle),
    "leaflet"
  )
})
