defaultSourceData: "ckan"           # for import of data
defaultSourceModel: "file"           # for import of models
# file types that are allowed for import from Pandora ("ckan")
ckanFileTypes:
  - "xls"
  - "xlsx"
  - "csv"
  - "odt"
  - "txt"
ckanModelTypes:
  - "zip"
  - "dssm"
githubRepo: "DSSM"        # for import of models
fileExtension: "dssm"      # for download of models
rPackageName: "DSSM"       # for download and import of models
